"""Adicion Activo a Tablas

Revision ID: 02ad7544331d
Revises: e5d525e51ec9
Create Date: 2024-07-28 06:03:16.366565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ad7544331d'
down_revision = 'e5d525e51ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('caracteristicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('sucursal', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('proveedor', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('fabricante', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('caracteristicas', schema=None) as batch_op:
        batch_op.drop_column('activo')

    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
