"""Modificacion Tabla Modelo

Revision ID: 49623b6e44f3
Revises: baabcaa8d2aa
Create Date: 2024-07-28 01:43:14.056445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49623b6e44f3'
down_revision = 'baabcaa8d2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint('modelo_ibfk_1', type_='foreignkey')
        batch_op.drop_column('categoria_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('modelo_ibfk_1', 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###
