"""Actualizacion Tabla Marcas.

Revision ID: 4cc658ff666b
Revises: 25a5efc3023c
Create Date: 2024-07-23 22:45:43.789430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc658ff666b'
down_revision = '25a5efc3023c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
