"""Modificacion Tabla Ventas

Revision ID: 5b1c98426d07
Revises: 5cb82375d636
Create Date: 2024-07-27 20:20:06.231084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b1c98426d07'
down_revision = '5cb82375d636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('producto', sa.String(length=100), nullable=True))
        batch_op.drop_constraint('venta_ibfk_2', type_='foreignkey')
        batch_op.drop_column('equipo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('venta_ibfk_2', 'equipo', ['equipo_id'], ['id'])
        batch_op.drop_column('producto')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
