"""add models

Revision ID: 0c6c0d7e15f3
Revises: 
Create Date: 2024-11-03 04:25:14.723089

"""

from werkzeug.security import generate_password_hash
from models import Usuario
from app import db

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0c6c0d7e15f3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accesorios",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("descripcion", sa.String(length=1000), nullable=False),
        sa.Column("precio", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "caracteristicas",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("descripcion", sa.String(length=1000), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categoria",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cliente",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("direccion", sa.String(length=50), nullable=False),
        sa.Column("telefono", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("fechaRegistro", sa.Date(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fabricante",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("origen", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inventario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=True),
        sa.Column("producto", sa.String(length=100), nullable=True),
        sa.Column("cantidadDisponible", sa.Integer(), nullable=True),
        sa.Column("ubicacionAlmacen", sa.String(length=100), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "modelo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("modelo", sa.String(length=50), nullable=False),
        sa.Column("anioLanzamiento", sa.Integer(), nullable=False),
        sa.Column("sistemaOperativo", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "proveedor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("contacto", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sucursal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("direccion", sa.String(length=50), nullable=False),
        sa.Column("telefono", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usuario",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=300), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "empleado",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("puesto", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("sucursal_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "marca",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=50), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("fabricante_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fabricante_id"],
            ["fabricante.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pedido",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("proveedor_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "venta",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=50), nullable=True),
        sa.Column("producto", sa.String(length=100), nullable=True),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("cliente_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cliente_id"],
            ["cliente.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equipo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("precio", sa.Integer(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=True),
        sa.Column("modelo_id", sa.Integer(), nullable=False),
        sa.Column("marca_id", sa.Integer(), nullable=False),
        sa.Column("caracteristicas_id", sa.Integer(), nullable=False),
        sa.Column("proveedor_id", sa.Integer(), nullable=False),
        sa.Column("categoria_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["caracteristicas_id"],
            ["caracteristicas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["categoria_id"],
            ["categoria.id"],
        ),
        sa.ForeignKeyConstraint(
            ["marca_id"],
            ["marca.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modelo_id"],
            ["modelo.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proveedor_id"],
            ["proveedor.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    existing_user = Usuario.query.filter_by(username="admin").first()

    if not existing_user:
        admin_user = Usuario(
            username="admin",
            password_hash=generate_password_hash("admin"),
            is_admin=True,
        )
        db.session.add(admin_user)
        db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equipo")
    op.drop_table("venta")
    op.drop_table("pedido")
    op.drop_table("marca")
    op.drop_table("empleado")
    op.drop_table("usuario")
    op.drop_table("sucursal")
    op.drop_table("proveedor")
    op.drop_table("modelo")
    op.drop_table("inventario")
    op.drop_table("fabricante")
    op.drop_table("cliente")
    op.drop_table("categoria")
    op.drop_table("caracteristicas")
    op.drop_table("accesorios")
    # ### end Alembic commands ###
