"""Actualizacion Stock cambia por Inventario-Logica de Inventario

Revision ID: 7116ec235ccc
Revises: 74785fca4cd3
Create Date: 2024-07-25 23:56:06.280192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7116ec235ccc'
down_revision = '74785fca4cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('marca_id', sa.Integer(), nullable=False),
    sa.Column('caracteristicas_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caracteristicas_id'], ['caracteristicas.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['marca_id'], ['marca.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock')
    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.drop_constraint('accesorios_ibfk_1', type_='foreignkey')
        batch_op.drop_column('stock_id')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('accesorios_ibfk_1', 'stock', ['stock_id'], ['id'])

    op.create_table('stock',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cantidadDisponible', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ubicacionAlmacen', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('equipo')
    # ### end Alembic commands ###
