"""Añadir stock a accesorios

Revision ID: ae539e4904b3
Revises: f70b4b4a5ad6
Create Date: 2024-07-25 19:00:28.944121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae539e4904b3'
down_revision = 'f70b4b4a5ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'stock', ['stock_id'], ['id'])

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caracteristicas_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('equipo_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('equipo_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'caracteristicas', ['caracteristicas_id'], ['id'])
        batch_op.drop_column('carateristicas_id')
        batch_op.drop_column('accesorios_id')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('equipo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accesorios_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('carateristicas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('equipo_ibfk_1', 'accesorios', ['accesorios_id'], ['id'])
        batch_op.create_foreign_key('equipo_ibfk_2', 'caracteristicas', ['carateristicas_id'], ['id'])
        batch_op.drop_column('caracteristicas_id')

    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stock_id')

    # ### end Alembic commands ###
