"""Modificacion Tabla Accesorios

Revision ID: baabcaa8d2aa
Revises: 5b1c98426d07
Create Date: 2024-07-27 20:27:08.291383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baabcaa8d2aa'
down_revision = '5b1c98426d07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesorios', schema=None) as batch_op:
        batch_op.drop_column('precio')

    # ### end Alembic commands ###
