"""Agregado Editar

Revision ID: e5d525e51ec9
Revises: 49623b6e44f3
Create Date: 2024-07-28 05:38:17.709602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d525e51ec9'
down_revision = '49623b6e44f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
