"""Actualizacion Tablas-Creacion Tabla Categoria.

Revision ID: f70b4b4a5ad6
Revises: 4cc658ff666b
Create Date: 2024-07-23 23:01:07.985384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f70b4b4a5ad6'
down_revision = '4cc658ff666b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('marca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', mysql.VARCHAR(length=50), nullable=False))

    op.drop_table('categoria')
    # ### end Alembic commands ###
